Add Meck Marketplace staking contract
valory-xyz/olas-operate-app pull request #402
Opened 2024-10-22 15:20 UTC by jmoreira-valory

## Proposed changes

Add Meck Marketplace staking contract

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-10-22 15:22 UTC, truemiller approved these changes

2024-10-22 15:23 UTC, truemiller requested changes
pls don't merge yet, need to confirm if there's mech changes

2024-10-23 07:59 UTC, truemiller approved these changes

2024-10-23 12:20 UTC, jmoreira-valory commented on templates/trader.yaml
> +service_version: v0.18.2
@0xArdi Confirm this version is OK. Version 0.19.0 is for multi-bet strategy, but was downgraded in QS.

2024-10-23 12:22 UTC, jmoreira-valory commented on operate/services/service.py
> +        )
@0xArdi Do we need to update further variables?. Same for Docker above.

2024-10-23 13:42 UTC, jmoreira-valory commented
We need the correct hash after @0xArdi updates `service.yaml` on the trader repository

2024-10-24 14:20 UTC, jmoreira-valory commented on templates/trader.yaml
> +service_version: v0.18.2
As discussed with @dagacha , version should be v0.18.2

2024-10-24 14:20 UTC, jmoreira-valory commented on frontend/constants/serviceTemplates.ts
> +    service_version: 'v0.18.2',
As discussed with @dagacha , version should be v0.18.2

2024-10-25 15:30 UTC, jmoreira-valory commented on operate/services/manage.py
> +        self._set_env_variables(hash=hash)
@0xArdi Although this approach is far from ideal, I think this is a cleaner, less error-prone way than what we had on [`Deployment._build_host`](https://github.com/valory-xyz/olas-operate-app/blob/main/operate/services/service.py#L581-L590) and [`Deployment._build_docker`](https://github.com/valory-xyz/olas-operate-app/blob/main/operate/services/service.py#L482-L494). 

I wonder why this approach was implemented this way (would the override as environment variable cause any issue?) Let me know any comments.

2024-10-29 10:42 UTC, iasonrovis approved these changes

2024-10-29 10:47 UTC, 0xArdi approved these changes

2024-10-29 11:12 UTC, merged